#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaData.DataAccess.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="InfoFileServer")]
	public partial class InfoFileServerDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public InfoFileServerDataContext() : 
				base(global::MetaData.DataAccess.Properties.Settings.Default.InfoFileServerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public InfoFileServerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoFileServerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoFileServerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public InfoFileServerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_FileInfo")]
		public int SP_FileInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fileInfoName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string filesize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Extension", DbType="VarChar(10)")] string extension, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DirectoryName", DbType="VarChar(50)")] string directoryName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastAccessTimeUtc", DbType="VarChar(50)")] string lastAccessTimeUtc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreationTime", DbType="VarChar(50)")] string creationTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastWriteTimeUtc", DbType="VarChar(50)")] string lastWriteTimeUtc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Attributes", DbType="VarChar(50)")] string attributes)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fileInfoName, filesize, extension, directoryName, lastAccessTimeUtc, creationTime, lastWriteTimeUtc, attributes);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
